//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by TLX_IRC.RC
//
#define IDC_PARSER_SETTINGS             3
#define IDM_ABOUTBOX                    0x0010
#define IDD_ABOUTBOX                    100
#define IDS_ABOUTBOX                    101
#define IDD_TLX_IRC_DIALOG              102
#define IDD_MAINWINDOW                  102
#define IDR_MAINFRAME                   128
#define IDI_MAINFRAME                   130
#define IDR_MAINMENU                    131
#define IDD_CONNMAN                     132
#define IDD_EDITTEXT                    134
#define IDD_PROFMAINPAGE                135
#define IDR_MENU1                       137
#define IDR_RUS_MAINMENU                137
#define IDD_PROFCONNPAGE                138
#define IDD_SETTINGS                    141
#define IDD_STATISTICS                  143
#define IDD_DIALOG1                     144
#define IDD_PARSER_S                    144
#define IDD_MENTIONWND                  146
#define IDC_LANGCOMBO1                  1000
#define IDC_SOCKMSGS                    1000
#define IDC_EDIT2                       1001
#define IDC_LANGLABEL                   1001
#define IDC_MSGTEXT                     1001
#define IDC_PORT                        1001
#define IDC_BUTTON1                     1002
#define IDC_PROFILES_GROUP              1002
#define IDC_SENDMSG                     1002
#define IDC_CLEAR_BUTTON                1002
#define IDC_CHANGE_MSG_FONT             1002
#define IDC_PROFILELIST                 1003
#define IDC_PROFNAME                    1003
#define IDC_ADD_PROFILE_BTN             1004
#define IDC_PROFNAME_LABEL              1004
#define IDC_CONNECT_PROFILE_BTN         1005
#define IDC_ENTERTEXTEDIT               1005
#define IDC_TECHINFO                    1005
#define IDC_NICKNAMES_LABEL             1005
#define IDC_CHANGE_PROFILE_BTN          1006
#define IDC_ENTERTEXTLABEL              1006
#define IDC_WINVER_LABEL                1006
#define IDC_DELETE_PROFILE_BTn          1007
#define IDC_WINVER                      1007
#define IDC_PASSWORD_LABEL              1007
#define IDC_PASSWORD                    1008
#define IDC_REALNAME_LABEL              1009
#define IDC_NICKNAMES                   1010
#define IDC_REALNAME                    1011
#define IDC_SERVER                      1011
#define IDC_SERVER_LABEL                1013
#define IDC_PORT_LABEL                  1014
#define IDC_ENCODING_LABEL              1015
#define IDC_ENCODING                    1016
#define IDC_WIN32S_EDITION              1020
#define IDC_LICENSE_NOTIFICATION        1021
#define IDC_COPYRIGHT                   1022
#define IDC_GITHUB_REPO_LINK            1023
#define IDC_SAVE_MSG_HISTORY            1025
#define IDC_JOINED_CHANNELS             1026
#define IDC_APPNAME                     1029
#define IDC_TRAFFIC_GROUP               1030
#define IDC_SENDED_LABEL                1031
#define IDC_SENDED_LABEL2               1032
#define IDC_SHOW_MSGTIME                1032
#define IDC_RECIEVED_LABEL              1033
#define IDC_TIMESTAMPS_POS              1033
#define IDC_RECIEVED_LABEL2             1034
#define IDC_PARSER_GROUP                1034
#define IDC_TOTAL_LABEL                 1035
#define IDC_TOTAL_LABEL2                1036
#define IDC_OPEN                        1036
#define IDC_MENTIONED_MSG               1037
#define IDC_TITLE                       1038
#define ID_FILE_CONNECT                 32771
#define ID_FILE_QUIT                    32772
#define ID_HELP_ABOUT                   32773
#define ID_VIEW_SETTINGS                32775
#define ID_FILE_STATISTICS              32776

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_3D_CONTROLS                     1
#define _APS_NEXT_RESOURCE_VALUE        147
#define _APS_NEXT_COMMAND_VALUE         32777
#define _APS_NEXT_CONTROL_VALUE         1039
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
